### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by pconwell** [appwrite/sdk-for-python#42]
### 👟 Reproduction steps

```
$ python3
>>> from appwrite.client import Client
```

### 👍 Expected behavior

Import the module

### 👎 Actual Behavior

```
ModuleNotFoundError: No module named 'appwrite.client'; 'appwrite' is not a package
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

No special installation/environment:

Debian 10
Python 3.7.3
Appwrite  v:0.12.0.200
Appwrite-Python 0.6.0

Here is a full trace:

```
pconwell@dev:~/appwrite_py$ sudo apt update && sudo apt upgrade -y
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://deb.debian.org/debian buster-updates InRelease                           
Hit:3 http://security.debian.org/debian-security buster/updates InRelease             
Get:4 https://pkgs.tailscale.com/stable/debian buster InRelease                       
Fetched 5,534 B in 1s (5,022 B/s)                              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

pconwell@dev:~/appwrite_py$ pip3 install appwrite
Requirement already satisfied: appwrite in /home/pconwell/.local/lib/python3.7/site-packages (0.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from appwrite) (2.27.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/pconwell/.local/lib/python3.7/site-packages (from requests->appwrite) (2020.6.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->appwrite) (1.26.8)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in /usr/local/lib/python3.7/dist-packages (from requests->appwrite) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in /usr/local/lib/python3.7/dist-packages (from requests->appwrite) (2.0.10)

pconwell@dev:~/appwrite_py$ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from appwrite.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pconwell/appwrite_py/appwrite.py", line 1, in <module>
    from appwrite.client import Client
ModuleNotFoundError: No module named 'appwrite.client'; 'appwrite' is not a package

>>> quit()
```

This could absolutely be user error, but I feel like this process is pretty straightforward so I'm not sure what I would be messing up.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)

**Comment by pconwell** [comment]
I just spun up a brand new Debian 11 VM and I am unable to reproduce this bug. There must be something misconfigured with my dev VM. I'll close this issue as it seems to be isolated to my machine.

I should have confirmed on another machine before opening the issue - sorry.
